const AUTO_PROSE_EN = 'Historical background will be expanded in future dataset updates'
const AUTO_PROSE_ZH = '歷史背景將在日後資料更新中擴充'

const LOCATED_AT_RE = /^Located at .+\.$/i
const LOCATED_AT_ZH_RE = /^位於.+。$/

function isUnknown(value) {
  const s = String(value ?? '').trim().toLowerCase()
  return !s || s === 'unknown' || s === 'unknown artist' || s === 'unknown medium' || s === 'untitled'
}

/**
 * @param {string | undefined | null} text
 */
export function isAutoGeneratedProse(text) {
  const s = String(text ?? '')
  return s.includes(AUTO_PROSE_EN) || s.includes(AUTO_PROSE_ZH)
}

/**
 * @param {string | undefined | null} text
 */
export function isBoilerplateLocationLine(text) {
  const s = String(text ?? '').trim()
  if (!s) return true
  return LOCATED_AT_RE.test(s) || LOCATED_AT_ZH_RE.test(s)
}

/**
 * @param {string | undefined | null} text
 */
export function hasSubstantiveText(text) {
  const s = String(text ?? '').trim()
  if (!s) return false
  if (isAutoGeneratedProse(s)) return false
  if (isBoilerplateLocationLine(s)) return false
  return true
}

/**
 * @param {Record<string, unknown>} artwork
 */
function pickFields(artwork) {
  return {
    title: String(artwork.displayTitle ?? artwork.title ?? '').trim(),
    artist: String(artwork.displayArtist ?? artwork.artist ?? '').trim(),
    year: String(artwork.displayYear ?? artwork.creation_year ?? artwork.year ?? '').trim(),
    medium: String(artwork.displayMedium ?? artwork.medium ?? '').trim(),
    museum: String(
      artwork.displayMuseumName ??
        artwork.museumName ??
        artwork.current_location?.museum ??
        ''
    ).trim(),
    city: String(artwork.displayCity ?? artwork.current_location?.city ?? '').trim(),
    country: String(artwork.displayCountry ?? artwork.current_location?.country ?? '').trim(),
    period: String(artwork.time_period ?? artwork.timePeriod ?? '').trim()
  }
}

/**
 * @param {number | null | undefined} lat
 * @param {number | null | undefined} lng
 */
export function formatGeoCue(lat, lng) {
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) return ''
  const latHem = lat >= 0 ? 'N' : 'S'
  const lngHem = lng >= 0 ? 'E' : 'W'
  return `${Math.abs(lat).toFixed(2)}°${latHem}, ${Math.abs(lng).toFixed(2)}°${lngHem}`
}

/**
 * Compose a short teaching summary from metadata when prose is thin.
 * @param {Record<string, unknown>} artwork
 * @param {(key: string, vars?: Record<string, string>) => string} t
 */
export function composeTeachingSummary(artwork, t) {
  const { title, artist, year, medium, museum, city, country, period } = pickFields(artwork)
  const safeTitle = isUnknown(title) ? t('unknown.title') : title
  const safeArtist = isUnknown(artist) ? t('unknown.artist') : artist
  const safeYear = isUnknown(year) ? t('unknown.year') : year
  const safeMedium = isUnknown(medium) ? t('unknown.medium') : medium

  const locationParts = [museum, city, country].filter((p) => p && !isUnknown(p))
  const location = locationParts.join(', ')

  const periodLabel = period && period !== 'unknown' ? t(`period.${period}`) : ''

  const vars = {
    title: safeTitle,
    artist: safeArtist,
    year: safeYear,
    medium: safeMedium,
    location: location || t('unknown.museum'),
    period: periodLabel
  }

  if (periodLabel) return t('present.summaryWithPeriod', vars)
  return t('present.summaryNoPeriod', vars)
}

/**
 * @param {Record<string, unknown>} artwork
 * @param {{ t: (key: string, vars?: Record<string, string>) => string }} options
 */
export function getTeachingSummary(artwork, { t }) {
  if (!artwork) return ''

  const curated = String(artwork.teaching_summary ?? '').trim()
  if (curated) return curated

  const historical =
    String(artwork.displayHistorical ?? artwork.historical_text ?? '').trim() ||
    String(artwork.displayDescription ?? artwork.description ?? '').trim()

  if (hasSubstantiveText(historical)) return historical

  return composeTeachingSummary(artwork, t)
}
