import { translate } from './translations.js'
import { museumNameToZhHant } from './museumNamesZhHant.js'
import { CONTENT_ZH_HANT_BY_ID } from './contentZhHant.js'
import { getCityForMuseum } from '../constants/museumCities.js'

const AUTO_PROSE_EN = 'Historical background will be expanded in future dataset updates'

function isAutoGeneratedProse(text) {
  return String(text ?? '').includes(AUTO_PROSE_EN)
}

function translateLocatedLine(text, tLocated) {
  const m = /^Located at (.+)\.$/i.exec(String(text ?? '').trim())
  if (!m) return null
  const inner = m[1].trim()
  const name = museumNameToZhHant(inner) || inner
  return tLocated(name)
}

function localizeBody(raw, overlay, key, displayTitle, displayArtist, t) {
  if (overlay[key]) return overlay[key]
  const text = String(raw ?? '')
  if (isAutoGeneratedProse(text)) {
    return t('fallback.prose', { title: displayTitle, artist: displayArtist })
  }
  const tLocated = (name) => translate('zhHant', 'locatedAt', { name })
  const line = translateLocatedLine(text, tLocated)
  return line ?? text
}

/**
 * Add display* fields for UI without mutating canonical filter/merge fields.
 */
export function localizeArtworkDisplay(art, locale) {
  if (!art || locale === 'en') {
    return {
      ...art,
      displayTitle: art.title,
      displayArtist: art.artist,
      displayMuseumName: art.museumName,
      displayCity: art.current_location?.city ?? '',
      displayCountry: art.current_location?.country ?? '',
      displayMedium: art.medium,
      displayYear: art.creation_year ?? art.year,
      displayDescription: art.historical_text || art.description || '',
      displayHistorical: art.historical_text || art.description || ''
    }
  }

  const t = (key, vars) => translate('zhHant', key, vars)
  const overlay = CONTENT_ZH_HANT_BY_ID[String(art.id)] ?? {}
  const museumEn = art.museumName ?? art.current_location?.museum ?? ''
  const museumZh = museumNameToZhHant(museumEn) || museumEn
  const cityZh = getCityForMuseum(museumEn, 'zhHant')

  const unknownArtist = t('unknown.artist')
  const unknownMedium = t('unknown.medium')
  const unknownYear = t('unknown.year')
  const unknownTitle = t('unknown.title')

  const displayTitle =
    overlay.title ?? (art.title === 'Untitled' ? unknownTitle : art.title)

  const displayArtist =
    overlay.artist ?? (art.artist === 'Unknown Artist' ? unknownArtist : art.artist)

  const displayMedium =
    overlay.medium ?? (art.medium === 'Unknown medium' ? unknownMedium : art.medium)

  const y = art.creation_year ?? art.year
  const displayYear = y === 'Unknown' ? unknownYear : y

  const displayHistorical = localizeBody(
    art.historical_text,
    overlay,
    'historical_text',
    displayTitle,
    displayArtist,
    t
  )

  const displayDescription = localizeBody(
    art.description,
    overlay,
    'description',
    displayTitle,
    displayArtist,
    t
  )

  return {
    ...art,
    displayTitle,
    displayArtist,
    displayMuseumName: museumZh,
    displayCity: cityZh || (art.current_location?.city ?? ''),
    displayCountry: art.current_location?.country ?? '',
    displayMedium,
    displayYear,
    displayDescription: displayHistorical || displayDescription,
    displayHistorical
  }
}
