import { translate } from './translations.js'
import { museumNameToZhHant } from './museumNamesZhHant.js'
import { CONTENT_ZH_HANT_BY_ID } from './contentZhHant.js'
import { CONTENT_ZH_HANT_GENERATED_BY_ID } from './contentZhHantGenerated.js'
import { getCityForMuseum } from '../constants/museumCities.js'

const AUTO_PROSE_EN = 'Historical background will be expanded in future dataset updates'

function isAutoGeneratedProse(text) {
  return String(text ?? '').includes(AUTO_PROSE_EN)
}

function translateLocatedLine(text, tLocated) {
  const m = /^Located at (.+)\.$/i.exec(String(text ?? '').trim())
  if (!m) return null
  const inner = m[1].trim()
  const name = museumNameToZhHant(inner) || inner
  return tLocated(name)
}

const COUNTRY_ZH_HANT = new Map([
  ['china', '中國'],
  ['japan', '日本'],
  ['korea', '韓國'],
  ['south korea', '韓國'],
  ['taiwan', '台灣'],
  ['france', '法國'],
  ['italy', '義大利'],
  ['spain', '西班牙'],
  ['netherlands', '荷蘭'],
  ['germany', '德國'],
  ['united kingdom', '英國'],
  ['uk', '英國'],
  ['united states', '美國'],
  ['usa', '美國'],
  ['canada', '加拿大'],
  ['australia', '澳洲'],
  ['new zealand', '紐西蘭'],
  ['india', '印度'],
  ['egypt', '埃及'],
  ['south africa', '南非'],
  ['russia', '俄羅斯'],
  ['philippines', '菲律賓'],
  ['singapore', '新加坡'],
  ['thailand', '泰國'],
  ['vietnam', '越南'],
  ['indonesia', '印尼'],
  ['malaysia', '馬來西亞']
])

const ARTIST_ZH_HANT = new Map([
  ['unknown artist', '未知藝術家'],
  ['johannes vermeer', '約翰尼斯・維梅爾'],
  ['pieter bruegel', '彼得・布勒哲爾'],
  ['francisco goya', '法蘭西斯科・哥雅'],
  ['pablo picasso', '巴勃羅・畢卡索'],
  ['andrei rublev', '安德烈・魯布列夫'],
  ['marc chagall', '馬克・夏卡爾'],
  ['mikhail vrubel', '米哈伊爾・弗魯貝爾'],
  ['eugène louis boudin', '歐仁・路易・布丹']
])

function mapCountryToZhHant(rawCountry) {
  const key = String(rawCountry ?? '').trim().toLowerCase()
  if (!key) return ''
  return COUNTRY_ZH_HANT.get(key) || rawCountry
}

function mapArtistToZhHant(rawArtist, unknownArtist) {
  const key = String(rawArtist ?? '').trim().toLowerCase()
  if (!key || key === 'unknown artist') return unknownArtist
  return ARTIST_ZH_HANT.get(key) || rawArtist
}

function localizeTitle(rawTitle, unknownTitle) {
  const title = String(rawTitle ?? '').trim()
  if (!title || title.toLowerCase() === 'untitled') return unknownTitle
  // Keep existing CJK as-is; otherwise wrap with Chinese book-title marks.
  if (/[\u3400-\u9FFF]/u.test(title)) return title
  return `《${title}》`
}

function localizeBody(raw, overlay, key, displayTitle, displayArtist, t) {
  if (overlay[key]) return overlay[key]
  const text = String(raw ?? '')
  if (isAutoGeneratedProse(text)) {
    return t('fallback.prose', { title: displayTitle, artist: displayArtist })
  }
  const tLocated = (name) => translate('zhHant', 'locatedAt', { name })
  const line = translateLocatedLine(text, tLocated)
  if (line) return line
  if (!text) return t('fallback.prose', { title: displayTitle, artist: displayArtist })
  if (/[\u3400-\u9FFF]/u.test(text)) return text
  return `（原文）${text}`
}

/**
 * Add display* fields for UI without mutating canonical filter/merge fields.
 */
export function localizeArtworkDisplay(art, locale) {
  if (!art || locale === 'en') {
    return {
      ...art,
      displayTitle: art.title,
      displayArtist: art.artist,
      displayMuseumName: art.museumName,
      displayCity: art.current_location?.city ?? '',
      displayCountry: art.current_location?.country ?? '',
      displayMedium: art.medium,
      displayYear: art.creation_year ?? art.year,
      displayDescription: art.historical_text || art.description || '',
      displayHistorical: art.historical_text || art.description || ''
    }
  }

  const t = (key, vars) => translate('zhHant', key, vars)
  const generated = CONTENT_ZH_HANT_GENERATED_BY_ID[String(art.id)] ?? {}
  const curated = CONTENT_ZH_HANT_BY_ID[String(art.id)] ?? {}
  const overlay = { ...generated, ...curated }
  const museumEn = art.museumName ?? art.current_location?.museum ?? ''
  const museumZh = museumNameToZhHant(museumEn) || museumEn
  const cityZh = getCityForMuseum(museumEn, 'zhHant')

  const unknownArtist = t('unknown.artist')
  const unknownMedium = t('unknown.medium')
  const unknownYear = t('unknown.year')
  const unknownTitle = t('unknown.title')

  const displayTitle = overlay.title ?? localizeTitle(art.title, unknownTitle)

  const displayArtist = overlay.artist ?? mapArtistToZhHant(art.artist, unknownArtist)

  const displayMedium =
    overlay.medium ?? (art.medium === 'Unknown medium' ? unknownMedium : art.medium)

  const y = art.creation_year ?? art.year
  const displayYear = y === 'Unknown' ? unknownYear : y

  const displayHistorical = localizeBody(
    art.historical_text,
    overlay,
    'historical_text',
    displayTitle,
    displayArtist,
    t
  )

  const displayDescription = localizeBody(
    art.description,
    overlay,
    'description',
    displayTitle,
    displayArtist,
    t
  )

  return {
    ...art,
    displayTitle,
    displayArtist,
    displayMuseumName: museumZh,
    displayCity: cityZh || (art.current_location?.city ?? ''),
    displayCountry: mapCountryToZhHant(art.current_location?.country ?? ''),
    displayMedium,
    displayYear,
    displayDescription: displayHistorical || displayDescription,
    displayHistorical
  }
}
