/**
 * Museum name -> city lookup.
 * Used to populate `current_location.city` when the dataset only provides `museumName` + coordinates.
 *
 * Note: Keys must match the exact museum names found in `src/artData.js` and `src/data/externalArtData.json`.
 */
export const MUSEUM_TO_CITY = {
  'Amon Carter Museum of American Art': { en: 'Fort Worth', zhHant: '沃思堡' },
  'Art Institute of Chicago': { en: 'Chicago', zhHant: '芝加哥' },
  'Asian Art Museum (SF)': { en: 'San Francisco', zhHant: '舊金山' },
  'Baltimore Museum of Art': { en: 'Baltimore', zhHant: '巴爾的摩' },
  'Bavarian State Painting Collections': { en: 'Munich', zhHant: '慕尼黑' },
  'Church of Santo Tomé': { en: 'Toledo', zhHant: '托利多' },
  'Condé Museum': { en: 'Chantilly', zhHant: '尚蒂伊' },
  'Courtauld Institute of Art': { en: 'London', zhHant: '倫敦' },
  'Dallas Museum of Art': { en: 'Dallas', zhHant: '達拉斯' },
  'Detroit Institute of Arts': { en: 'Detroit', zhHant: '底特律' },
  'Dominikanerkloster Frankfurt am Main': { en: 'Frankfurt am Main', zhHant: '法蘭克福' },
  'Fogg Museum': { en: 'Cambridge', zhHant: '劍橋' },
  "Galleria Nazionale d'Arte Antica": { en: 'Rome', zhHant: '羅馬' },
  'Gemäldegalerie Berlin': { en: 'Berlin', zhHant: '柏林' },
  'Historical Museum Frankfurt': { en: 'Frankfurt am Main', zhHant: '法蘭克福' },
  'Hugh Lane Gallery': { en: 'Dublin', zhHant: '都柏林' },
  'Independence Hall': { en: 'Philadelphia', zhHant: '費城' },
  'J. Paul Getty Museum': { en: 'Los Angeles', zhHant: '洛杉磯' },
  'Joslyn Art Museum': { en: 'Omaha', zhHant: '奧馬哈' },
  'Kyoto National Museum': { en: 'Kyoto', zhHant: '京都' },
  'Marienkirche': { en: 'Dortmund', zhHant: '多特蒙德' },
  'Mauritshuis': { en: 'The Hague', zhHant: '海牙' },
  'Metropolitan Museum of Art': { en: 'New York', zhHant: '紐約' },
  'Minneapolis Institute of Art': { en: 'Minneapolis', zhHant: '明尼阿波利斯' },
  'Munich Residence': { en: 'Munich', zhHant: '慕尼黑' },
  "Musée d'art moderne de Paris": { en: 'Paris', zhHant: '巴黎' },
  "Musée d'Orsay": { en: 'Paris', zhHant: '巴黎' },
  'Museo de Arte de Ponce': { en: 'Ponce', zhHant: '庞塞' },
  'Museo de la Trinidad': { en: 'Madrid', zhHant: '馬德里' },
  'Museo del Prado': { en: 'Madrid', zhHant: '馬德里' },
  'Museo di Capodimonte': { en: 'Naples', zhHant: '那不勒斯' },
  'Museum Mayer van den Bergh': { en: 'Antwerp', zhHant: '安特衛普' },
  'Museum of Fine Arts Boston': { en: 'Boston', zhHant: '波士頓' },
  'Museum of Islamic Art, Doha': { en: 'Doha', zhHant: '多哈' },
  'Museum of Modern Art': { en: 'New York', zhHant: '紐約' },
  'Museum of the History of France': { en: 'Versailles', zhHant: '凡爾賽' },
  'National Gallery': { en: 'London', zhHant: '倫敦' },
  'National Gallery of Art': { en: 'Washington, D.C.', zhHant: '華盛頓特區' },
  'National Gallery of Canada': { en: 'Ottawa', zhHant: '渥太華' },
  'National Museum in Gdańsk': { en: 'Gdańsk', zhHant: '格但斯克' },
  'National Museum in Kraków': { en: 'Kraków', zhHant: '克拉科夫' },
  'National Museum of Korea': { en: 'Seoul', zhHant: '首爾' },
  'National Museum of Western Art': { en: 'Tokyo', zhHant: '東京' },
  'National Museum, New Delhi': { en: 'New Delhi', zhHant: '新德里' },
  'National Palace Museum': { en: 'Taipei', zhHant: '台北' },
  'Palace Museum, Beijing': { en: 'Beijing', zhHant: '北京' },
  'Peggy Guggenheim Collection': { en: 'Venice', zhHant: '威尼斯' },
  'Pinacoteca Vaticana': { en: 'Vatican City', zhHant: '梵蒂岡' },
  'Pushkin Museum of Fine Arts': { en: 'Moscow', zhHant: '莫斯科' },
  'Rijksmuseum': { en: 'Amsterdam', zhHant: '阿姆斯特丹' },
  'San Michele Visdomini': { en: 'Florence', zhHant: '佛羅倫斯' },
  'Scuola Grande di San Rocco': { en: 'Venice', zhHant: '威尼斯' },
  'Shanghai Museum': { en: 'Shanghai', zhHant: '上海' },
  'Staatliche Kunsthalle Karlsruhe': { en: 'Karlsruhe', zhHant: '卡爾斯魯厄' },
  'Staatliche Kunstsammlungen Dresden': { en: 'Dresden', zhHant: '德累斯頓' },
  'Städel Museum': { en: 'Frankfurt am Main', zhHant: '法蘭克福' },
  'The Frick Collection': { en: 'New York', zhHant: '紐約' },
  'Tokyo National Museum': { en: 'Tokyo', zhHant: '東京' },
  // Disambiguate from Toledo, Spain (Church of Santo Tomé)
  'Toledo Museum of Art': { en: 'Toledo, Ohio', zhHant: '托萊多（俄亥俄州）' },
  'Topkapi Palace Museum': { en: 'Istanbul', zhHant: '伊斯坦堡' },
  'Uffizi Gallery': { en: 'Florence', zhHant: '佛羅倫斯' },
  'Von der Heydt Museum': { en: 'Wuppertal', zhHant: '瓦珀塔爾' },

  // Australia / New Zealand / Southeast Asia (Wikidata & externalArtData)
  'National Gallery of Australia': { en: 'Canberra', zhHant: '坎培拉' },
  'National Gallery of Victoria': { en: 'Melbourne', zhHant: '墨爾本' },
  'Art Gallery of New South Wales': { en: 'Sydney', zhHant: '雪梨' },
  'Queensland Art Gallery': { en: 'Brisbane', zhHant: '布里斯本' },
  'Art Gallery of South Australia': { en: 'Adelaide', zhHant: '阿德萊德' },
  'Museum of Contemporary Art Australia': { en: 'Sydney', zhHant: '雪梨' },
  'National Portrait Gallery of Australia': { en: 'Canberra', zhHant: '坎培拉' },
  'Auckland Art Gallery': { en: 'Auckland', zhHant: '奧克蘭' },
  'Te Papa Tongarewa': { en: 'Wellington', zhHant: '惠靈頓' },
  'Museum of New Zealand Te Papa Tongarewa': { en: 'Wellington', zhHant: '惠靈頓' },
  'National Gallery Singapore': { en: 'Singapore', zhHant: '新加坡' },
  'National Museum of Singapore': { en: 'Singapore', zhHant: '新加坡' },
  'Singapore Art Museum': { en: 'Singapore', zhHant: '新加坡' },
  'National Museum of Indonesia': { en: 'Jakarta', zhHant: '雅加達' },
  'Museum of Fine Arts and Ceramics, Jakarta': { en: 'Jakarta', zhHant: '雅加達' },
  'Bangkok National Museum': { en: 'Bangkok', zhHant: '曼谷' },
  'National Museum Bangkok': { en: 'Bangkok', zhHant: '曼谷' },
  'Bangkok Art and Culture Centre': { en: 'Bangkok', zhHant: '曼谷' },
  'Vietnam Museum of Fine Arts': { en: 'Hanoi', zhHant: '河內' },
  'Vietnam National Museum of Fine Arts': { en: 'Hanoi', zhHant: '河內' },
  'Ho Chi Minh City Museum of Fine Arts': { en: 'Ho Chi Minh City', zhHant: '胡志明市' },
  'National Art Gallery, Malaysia': { en: 'Kuala Lumpur', zhHant: '吉隆坡' },
  'Penang Museum': { en: 'Georgetown', zhHant: '喬治市' },
  'National Museum of Fine Arts, Philippines': { en: 'Manila', zhHant: '馬尼拉' },
  'Ayala Museum': { en: 'Makati', zhHant: '馬卡蒂' },
  'National Portrait Gallery': { en: 'Canberra', zhHant: '坎培拉' },
  'Australian Sports Museum': { en: 'Melbourne', zhHant: '墨爾本' },
  'Australian War Memorial': { en: 'Canberra', zhHant: '坎培拉' },
  'Art Gallery of Western Australia': { en: 'Perth', zhHant: '珀斯' },
  'Art Gallery of Ballarat': { en: 'Ballarat', zhHant: '巴拉瑞特' },
  'Geelong Art Gallery': { en: 'Geelong', zhHant: '吉朗' },
  'Dunedin Public Art Gallery': { en: 'Dunedin', zhHant: '但尼丁' },
  'Auckland Art Gallery Toi o Tāmaki': { en: 'Auckland', zhHant: '奧克蘭' },
  'Lopez Museum': { en: 'Manila', zhHant: '馬尼拉' },
  'Metropolitan Museum of Manila': { en: 'Manila', zhHant: '馬尼拉' },
  'Malacañang Palace': { en: 'Manila', zhHant: '馬尼拉' },
  'Gedung Agung': { en: 'Yogyakarta', zhHant: '日惹' }

  // Africa (Wikidata + externalArtData)
  // City labels are based on representative artwork coordinates from `externalArtData.json`.
  // Traditional Chinese labels for Africa coverage.
  ,
  'National Museum of Fine Arts of Algiers': { en: 'Algiers', zhHant: '阿爾及爾' },
  'South African National Gallery': { en: 'Cape Town', zhHant: '開普敦' },
  'Mohamed Mahmoud Khalil Museum': { en: 'Cairo', zhHant: '開羅' },
  'Iziko William Fehr Collection (Castle of Good Hope)': { en: 'Cape Town', zhHant: '開普敦' },
  'Johannesburg Art Gallery': { en: 'Johannesburg', zhHant: '約翰尼斯堡' },
  'Michaelis Collection': { en: 'Cape Town', zhHant: '開普敦' },
  'Saint Catherine Monastery': { en: 'Saint Catherine', zhHant: '聖凱瑟琳' },
  'Theban Tomb 69': { en: 'Luxor', zhHant: '盧克索' },
  'Egyptian Museum': { en: 'Cairo', zhHant: '開羅' },
  'Ethnological Museum of Addis Ababa': { en: 'Addis Ababa', zhHant: '阿迪斯阿貝巴' },
  'North-West University': { en: 'Mahikeng', zhHant: '馬菲肯' },
  'Cirta National Museum': { en: 'Constantine', zhHant: '君士坦丁' },
  'Ahmed Zabana National Museum': { en: 'Oran', zhHant: '奧蘭' }
}

export function getCityForMuseum(museumName, locale = 'en') {
  const row = MUSEUM_TO_CITY[museumName]
  if (!row) return ''
  if (locale === 'zhHant') return row.zhHant ?? ''
  return row.en ?? ''
}

