export const artworks = [
  {
    id: 1,
    title: 'Mademoiselle V. . . in the Costume of an Espada',
    artist: 'Édouard Manet',
    year: 1862,
    lat: 40.779444444,
    lng: -73.963333333,
    imageUrl: '/artworks/_oss/art-1.jpg',
    description: 'Located at Metropolitan Museum of Art.',
    museumName: 'Metropolitan Museum of Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q72650'
  },
  {
    id: 2,
    title: 'La loge',
    artist: 'Pierre-Auguste Renoir',
    year: 1874,
    lat: 51.510734,
    lng: -0.116912,
    imageUrl: '/artworks/_oss/art-2.jpg',
    description: 'Located at Courtauld Institute of Art.',
    museumName: 'Courtauld Institute of Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q74339'
  },
  {
    id: 3,
    title: 'Dull Gret',
    artist: 'Pieter Brueghel the Elder',
    year: 1563,
    lat: 51.215517,
    lng: 4.405316,
    imageUrl: '/artworks/_oss/art-3.jpg',
    description: 'Located at Museum Mayer van den Bergh.',
    museumName: 'Museum Mayer van den Bergh',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q80869'
  },
  {
    id: 4,
    title: 'Nighthawks',
    artist: 'Edward Hopper',
    year: 1942,
    lat: 41.879444444,
    lng: -87.623888888,
    imageUrl: '/artworks/_oss/art-4.jpg',
    description: 'Located at Art Institute of Chicago.',
    museumName: 'Art Institute of Chicago',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q83872'
  },
  {
    id: 5,
    title: 'Saint Praxedis',
    artist: 'Johannes Vermeer',
    year: 1655,
    lat: 35.7153567,
    lng: 139.7758498,
    imageUrl: '/artworks/_oss/art-5.jpg',
    description: 'Located at National Museum of Western Art.',
    museumName: 'National Museum of Western Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q94006'
  },
  {
    id: 6,
    title: 'The Burial of the Count of Orgaz',
    artist: 'El Greco',
    year: 1586,
    lat: 39.856822222,
    lng: -4.028133333,
    imageUrl: '/artworks/_oss/art-6.jpg',
    description: 'Located at Church of Santo Tomé.',
    museumName: 'Church of Santo Tomé',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q94802'
  },
  {
    id: 7,
    title: 'Young man in Mayo costume',
    artist: 'Édouard Manet',
    year: 1863,
    lat: 40.779444444,
    lng: -73.963333333,
    imageUrl: '/artworks/_oss/art-7.jpg',
    description: 'Located at Metropolitan Museum of Art.',
    museumName: 'Metropolitan Museum of Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q113262'
  },
  {
    id: 8,
    title: 'Portrait of Monsieur and Madame Auguste Manet',
    artist: 'Édouard Manet',
    year: 1860,
    lat: 48.86,
    lng: 2.326388888,
    imageUrl: '/artworks/_oss/art-8.jpg',
    description: 'Located at Musée d\'Orsay.',
    museumName: 'Musée d\'Orsay',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q126467'
  },
  {
    id: 9,
    title: 'Portrait of Monsieur and Madame Auguste Manet',
    artist: 'Édouard Manet',
    year: 1860,
    lat: 48.859972,
    lng: 2.326527,
    imageUrl: '/artworks/_oss/art-9.jpg',
    description: 'Located at Musée d\'Orsay.',
    museumName: 'Musée d\'Orsay',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q126467'
  },
  {
    id: 10,
    title: 'Still Life with Beer Mug and Fruit',
    artist: 'Vincent van Gogh',
    year: 1881,
    lat: 51.2573,
    lng: 7.14658,
    imageUrl: '/artworks/_oss/art-10.jpg',
    description: 'Located at Von der Heydt Museum.',
    museumName: 'Von der Heydt Museum',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q152123'
  },
  {
    id: 11,
    title: 'Still Life with Beer Mug and Fruit',
    artist: 'http://www.wikidata.org/.well-known/genid/b49fc34b8b333d48615fa6bce6c9ad9c',
    year: 1881,
    lat: 51.2573,
    lng: 7.14658,
    imageUrl: '/artworks/_oss/art-11.jpg',
    description: 'Located at Von der Heydt Museum.',
    museumName: 'Von der Heydt Museum',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q152123'
  },
  {
    id: 12,
    title: 'La fornarina',
    artist: 'Raphael',
    year: 1519,
    lat: 41.902779717,
    lng: 12.489527499,
    imageUrl: '/artworks/_oss/art-12.jpg',
    description: 'Located at Galleria Nazionale d\'Arte Antica.',
    museumName: 'Galleria Nazionale d\'Arte Antica',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q153441'
  },
  {
    id: 13,
    title: 'Woman in Blue Reading a Letter',
    artist: 'Johannes Vermeer',
    year: 1664,
    lat: 52.36,
    lng: 4.885277777,
    imageUrl: '/artworks/_oss/art-13.jpg',
    description: 'Located at Rijksmuseum.',
    museumName: 'Rijksmuseum',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q166937'
  },
  {
    id: 14,
    title: 'The Milkmaid',
    artist: 'Johannes Vermeer',
    year: 1660,
    lat: 52.36,
    lng: 4.885277777,
    imageUrl: '/artworks/_oss/art-14.jpg',
    description: 'Located at Rijksmuseum.',
    museumName: 'Rijksmuseum',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q167605'
  },
  {
    id: 15,
    title: 'Congress Voting Independence',
    artist: 'Robert Edge Pine',
    year: 1784,
    lat: 39.948888888,
    lng: -75.15,
    imageUrl: '/artworks/_oss/art-15.jpg',
    description: 'Located at Independence Hall.',
    museumName: 'Independence Hall',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q176923'
  },
  {
    id: 16,
    title: 'The Return of Spring',
    artist: 'William-Adolphe Bouguereau',
    year: 1886,
    lat: 41.260254,
    lng: -95.946022,
    imageUrl: '/artworks/_oss/art-16.jpg',
    description: 'Located at Joslyn Art Museum.',
    museumName: 'Joslyn Art Museum',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q431571'
  },
  {
    id: 17,
    title: 'The Last Judgment',
    artist: 'Hans Memling',
    year: 1469,
    lat: 54.345425,
    lng: 18.64691389,
    imageUrl: '/artworks/_oss/art-17.jpg',
    description: 'Located at National Museum in Gdańsk.',
    museumName: 'National Museum in Gdańsk',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q701035'
  },
  {
    id: 18,
    title: 'The Fif',
    artist: 'Édouard Manet',
    year: 1866,
    lat: 48.86,
    lng: 2.326388888,
    imageUrl: '/artworks/_oss/art-18.jpg',
    description: 'Located at Musée d\'Orsay.',
    museumName: 'Musée d\'Orsay',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q26250'
  },
  {
    id: 19,
    title: 'Diana and her Nymphs',
    artist: 'Johannes Vermeer',
    year: 1650,
    lat: 52.080388888,
    lng: 4.314305555,
    imageUrl: '/artworks/_oss/art-19.jpg',
    description: 'Located at Mauritshuis.',
    museumName: 'Mauritshuis',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q32234'
  },
  {
    id: 20,
    title: 'Street Singer',
    artist: 'Édouard Manet',
    year: 1862,
    lat: 42.339444444,
    lng: -71.094166666,
    imageUrl: '/artworks/_oss/art-20.jpg',
    description: 'Located at Museum of Fine Arts Boston.',
    museumName: 'Museum of Fine Arts Boston',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q39226'
  },
  {
    id: 21,
    title: 'Lola de Valence',
    artist: 'Édouard Manet',
    year: 1862,
    lat: 48.86,
    lng: 2.326388888,
    imageUrl: '/artworks/_oss/art-21.jpg',
    description: 'Located at Musée d\'Orsay.',
    museumName: 'Musée d\'Orsay',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q44124'
  },
  {
    id: 22,
    title: 'The Starry Night',
    artist: 'Vincent van Gogh',
    year: 1889,
    lat: 40.761444444,
    lng: -73.977611111,
    imageUrl: '/artworks/_oss/art-22.jpg',
    description: 'Located at Museum of Modern Art.',
    museumName: 'Museum of Modern Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q45585'
  },
  {
    id: 23,
    title: 'Las Meninas',
    artist: 'Diego Velázquez',
    year: 1656,
    lat: 40.413888888,
    lng: -3.692222222,
    imageUrl: '/artworks/_oss/art-23.jpg',
    description: 'Located at Museo del Prado.',
    museumName: 'Museo del Prado',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q208758'
  },
  {
    id: 24,
    title: 'Music in the Tuileries',
    artist: 'Édouard Manet',
    year: 1862,
    lat: 51.508888888,
    lng: -0.128333333,
    imageUrl: '/artworks/_oss/art-24.jpg',
    description: 'Located at National Gallery.',
    museumName: 'National Gallery',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q210277'
  },
  {
    id: 25,
    title: 'Music in the Tuileries',
    artist: 'Édouard Manet',
    year: 1862,
    lat: 53.354166666,
    lng: -6.264722222,
    imageUrl: '/artworks/_oss/art-25.jpg',
    description: 'Located at Hugh Lane Gallery.',
    museumName: 'Hugh Lane Gallery',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q210277'
  },
  {
    id: 26,
    title: 'The Slave Ship',
    artist: 'J. M. W. Turner',
    year: 1840,
    lat: 42.339444444,
    lng: -71.094166666,
    imageUrl: '/artworks/_oss/art-26.jpg',
    description: 'Located at Museum of Fine Arts Boston.',
    museumName: 'Museum of Fine Arts Boston',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q219344'
  },
  {
    id: 27,
    title: 'Arnolfini Portrait',
    artist: 'Jan van Eyck',
    year: 1434,
    lat: 51.508888888,
    lng: -0.128333333,
    imageUrl: '/artworks/_oss/art-27.jpg',
    description: 'Located at National Gallery.',
    museumName: 'National Gallery',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q220859'
  },
  {
    id: 28,
    title: 'The Battle of Alexander at Issus',
    artist: 'Albrecht Altdorfer',
    year: 1529,
    lat: 48.149583,
    lng: 11.571776,
    imageUrl: '/artworks/_oss/art-28.jpg',
    description: 'Located at Bavarian State Painting Collections.',
    museumName: 'Bavarian State Painting Collections',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q241455'
  },
  {
    id: 29,
    title: 'Alba Madonna',
    artist: 'Raphael',
    year: 1511,
    lat: 38.891388888,
    lng: -77.02,
    imageUrl: '/artworks/_oss/art-29.jpg',
    description: 'Located at National Gallery of Art.',
    museumName: 'National Gallery of Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q254923'
  },
  {
    id: 30,
    title: 'The Fighting Temeraire',
    artist: 'J. M. W. Turner',
    year: 1839,
    lat: 51.508888888,
    lng: -0.128333333,
    imageUrl: '/artworks/_oss/art-30.jpg',
    description: 'Located at National Gallery.',
    museumName: 'National Gallery',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q257580'
  },
  {
    id: 31,
    title: 'Germania',
    artist: 'Philipp Veit',
    year: 1836,
    lat: 50.10322,
    lng: 8.67388,
    imageUrl: '/artworks/_oss/art-31.jpg',
    description: 'Located at Städel Museum.',
    museumName: 'Städel Museum',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q265201'
  },
  {
    id: 32,
    title: 'Mérode Altarpiece',
    artist: 'http://www.wikidata.org/.well-known/genid/f1664f0be42080933843168150f70f32',
    year: 1500,
    lat: 40.779444444,
    lng: -73.963333333,
    imageUrl: '/artworks/_oss/art-32.jpg',
    description: 'Located at Metropolitan Museum of Art.',
    museumName: 'Metropolitan Museum of Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q285392'
  },
  {
    id: 33,
    title: 'Prussian Homage',
    artist: 'Jan Matejko',
    year: 1879,
    lat: 50.060277777,
    lng: 19.923888888,
    imageUrl: '/artworks/_oss/art-33.jpg',
    description: 'Located at National Museum in Kraków.',
    museumName: 'National Museum in Kraków',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q317261'
  },
  {
    id: 34,
    title: 'The Garden of Earthly Delights',
    artist: 'Hieronymus Bosch',
    year: 1490,
    lat: 40.413888888,
    lng: -3.692222222,
    imageUrl: '/artworks/_oss/art-34.jpg',
    description: 'Located at Museo del Prado.',
    museumName: 'Museo del Prado',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q321303'
  },
  {
    id: 35,
    title: 'Dresden Triptych',
    artist: 'Jan van Eyck',
    year: 1437,
    lat: 51.0528,
    lng: 13.7369,
    imageUrl: '/artworks/_oss/art-35.jpg',
    description: 'Located at Staatliche Kunstsammlungen Dresden.',
    museumName: 'Staatliche Kunstsammlungen Dresden',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q323079'
  },
  {
    id: 36,
    title: 'Heller Altarpiece',
    artist: 'Albrecht Dürer',
    year: 1610,
    lat: 50.10322,
    lng: 8.67388,
    imageUrl: '/artworks/_oss/art-36.jpg',
    description: 'Located at Städel Museum.',
    museumName: 'Städel Museum',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q323141'
  },
  {
    id: 37,
    title: 'Heller Altarpiece',
    artist: 'Albrecht Dürer',
    year: 1610,
    lat: 50.1097,
    lng: 8.6825,
    imageUrl: '/artworks/_oss/art-37.jpg',
    description: 'Located at Historical Museum Frankfurt.',
    museumName: 'Historical Museum Frankfurt',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q323141'
  },
  {
    id: 38,
    title: 'Heller Altarpiece',
    artist: 'Matthias Grünewald',
    year: 1610,
    lat: 50.10322,
    lng: 8.67388,
    imageUrl: '/artworks/_oss/art-38.jpg',
    description: 'Located at Städel Museum.',
    museumName: 'Städel Museum',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q323141'
  },
  {
    id: 39,
    title: 'Heller Altarpiece',
    artist: 'Matthias Grünewald',
    year: 1610,
    lat: 50.1117,
    lng: 8.68778,
    imageUrl: '/artworks/_oss/art-39.jpg',
    description: 'Located at Dominikanerkloster Frankfurt am Main.',
    museumName: 'Dominikanerkloster Frankfurt am Main',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q323141'
  },
  {
    id: 40,
    title: 'Heller Altarpiece',
    artist: 'Jobst Harrich',
    year: 1610,
    lat: 48.141049105,
    lng: 11.578714243,
    imageUrl: '/artworks/_oss/art-40.jpg',
    description: 'Located at Munich Residence.',
    museumName: 'Munich Residence',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q323141'
  },
  {
    id: 41,
    title: 'Heller Altarpiece',
    artist: 'http://www.wikidata.org/.well-known/genid/13f2bd0795b0d518c703a2cbff80f758',
    year: 1610,
    lat: 49.0119,
    lng: 8.4,
    imageUrl: '/artworks/_oss/art-41.jpg',
    description: 'Located at Staatliche Kunsthalle Karlsruhe.',
    museumName: 'Staatliche Kunsthalle Karlsruhe',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q323141'
  },
  {
    id: 42,
    title: 'Heller Altarpiece',
    artist: 'Albrecht Dürer',
    year: 1500,
    lat: 50.1097,
    lng: 8.6825,
    imageUrl: '/artworks/_oss/art-42.jpg',
    description: 'Located at Historical Museum Frankfurt.',
    museumName: 'Historical Museum Frankfurt',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q323141'
  },
  {
    id: 43,
    title: 'Heller Altarpiece',
    artist: 'Albrecht Dürer',
    year: 1500,
    lat: 50.1117,
    lng: 8.68778,
    imageUrl: '/artworks/_oss/art-43.jpg',
    description: 'Located at Dominikanerkloster Frankfurt am Main.',
    museumName: 'Dominikanerkloster Frankfurt am Main',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q323141'
  },
  {
    id: 44,
    title: 'Heller Altarpiece',
    artist: 'Matthias Grünewald',
    year: 1500,
    lat: 48.141049105,
    lng: 11.578714243,
    imageUrl: '/artworks/_oss/art-44.jpg',
    description: 'Located at Munich Residence.',
    museumName: 'Munich Residence',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q323141'
  },
  {
    id: 45,
    title: 'Heller Altarpiece',
    artist: 'Jobst Harrich',
    year: 1500,
    lat: 49.0119,
    lng: 8.4,
    imageUrl: '/artworks/_oss/art-45.jpg',
    description: 'Located at Staatliche Kunsthalle Karlsruhe.',
    museumName: 'Staatliche Kunsthalle Karlsruhe',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q323141'
  },
  {
    id: 46,
    title: 'Heller Altarpiece',
    artist: 'http://www.wikidata.org/.well-known/genid/13f2bd0795b0d518c703a2cbff80f758',
    year: 1500,
    lat: 50.1097,
    lng: 8.6825,
    imageUrl: '/artworks/_oss/art-46.jpg',
    description: 'Located at Historical Museum Frankfurt.',
    museumName: 'Historical Museum Frankfurt',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q323141'
  },
  {
    id: 47,
    title: 'Marienaltar',
    artist: 'Conrad von Soest',
    year: 1400,
    lat: 51.5142,
    lng: 7.4675,
    imageUrl: '/artworks/_oss/art-47.jpg',
    description: 'Located at Marienkirche.',
    museumName: 'Marienkirche',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q323155'
  },
  {
    id: 48,
    title: 'Madonna Diotallevi',
    artist: 'Raphael',
    year: 1502,
    lat: 52.508611111,
    lng: 13.364722222,
    imageUrl: '/artworks/_oss/art-48.jpg',
    description: 'Located at Gemäldegalerie Berlin.',
    museumName: 'Gemäldegalerie Berlin',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q323188'
  },
  {
    id: 49,
    title: 'Assumption of the Virgin',
    artist: 'Francesco Botticini',
    year: 1476,
    lat: 51.508888888,
    lng: -0.128333333,
    imageUrl: '/artworks/_oss/art-49.jpg',
    description: 'Located at National Gallery.',
    museumName: 'National Gallery',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q323753'
  },
  {
    id: 50,
    title: 'Assumption of the Virgin',
    artist: 'Francesco Botticini',
    year: 1475,
    lat: 51.508888888,
    lng: -0.128333333,
    imageUrl: '/artworks/_oss/art-50.jpg',
    description: 'Located at National Gallery.',
    museumName: 'National Gallery',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q323753'
  },
  {
    id: 51,
    title: 'Assumption of the Virgin',
    artist: 'Andrea del Castagno',
    year: 1449,
    lat: 52.508611111,
    lng: 13.364722222,
    imageUrl: '/artworks/_oss/art-51.jpg',
    description: 'Located at Gemäldegalerie Berlin.',
    museumName: 'Gemäldegalerie Berlin',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q430277'
  },
  {
    id: 52,
    title: 'Garden at Sainte-Adresse',
    artist: 'Claude Monet',
    year: 1867,
    lat: 40.779444444,
    lng: -73.963333333,
    imageUrl: '/artworks/_oss/art-52.jpg',
    description: 'Located at Metropolitan Museum of Art.',
    museumName: 'Metropolitan Museum of Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q432253'
  },
  {
    id: 53,
    title: 'Adoration of the Magi',
    artist: 'Sandro Botticelli',
    year: 1475,
    lat: 43.768333333,
    lng: 11.255277777,
    imageUrl: '/artworks/_oss/art-53.jpg',
    description: 'Located at Uffizi Gallery.',
    museumName: 'Uffizi Gallery',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q488825'
  },
  {
    id: 54,
    title: 'Crucifixion',
    artist: 'Jacopo Tintoretto',
    year: 1565,
    lat: 45.436571,
    lng: 12.325309,
    imageUrl: '/artworks/_oss/art-54.jpg',
    description: 'Located at Scuola Grande di San Rocco.',
    museumName: 'Scuola Grande di San Rocco',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q490312'
  },
  {
    id: 55,
    title: 'The Dream of a Knight',
    artist: 'Raphael',
    year: 1504,
    lat: 51.508888888,
    lng: -0.128333333,
    imageUrl: '/artworks/_oss/art-55.jpg',
    description: 'Located at National Gallery.',
    museumName: 'National Gallery',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q552040'
  },
  {
    id: 56,
    title: 'Self-portrait',
    artist: 'Raphael',
    year: 1505,
    lat: 43.768333333,
    lng: 11.255277777,
    imageUrl: '/artworks/_oss/art-56.jpg',
    description: 'Located at Uffizi Gallery.',
    museumName: 'Uffizi Gallery',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q555821'
  },
  {
    id: 57,
    title: 'The Icebergs',
    artist: 'Frederic Edwin Church',
    year: 1861,
    lat: 32.78756,
    lng: -96.800893,
    imageUrl: '/artworks/_oss/art-57.jpg',
    description: 'Located at Dallas Museum of Art.',
    museumName: 'Dallas Museum of Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q575573'
  },
  {
    id: 58,
    title: 'The Icebergs',
    artist: 'Frederic Edwin Church',
    year: 1861,
    lat: 32.78756,
    lng: -96.800893,
    imageUrl: '/artworks/_oss/art-58.jpg',
    description: 'Located at Dallas Museum of Art.',
    museumName: 'Dallas Museum of Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q575573'
  },
  {
    id: 59,
    title: 'Pucci Altarpiece',
    artist: 'Pontormo',
    year: 1518,
    lat: 43.7739,
    lng: 11.258,
    imageUrl: '/artworks/_oss/art-59.jpg',
    description: 'Located at San Michele Visdomini.',
    museumName: 'San Michele Visdomini',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q596677'
  },
  {
    id: 60,
    title: 'The Crown of Thorns',
    artist: 'Anthony van Dyck',
    year: 1620,
    lat: 40.413888888,
    lng: -3.692222222,
    imageUrl: '/artworks/_oss/art-60.jpg',
    description: 'Located at Museo del Prado.',
    museumName: 'Museo del Prado',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q609576'
  },
  {
    id: 61,
    title: 'The Resurrection',
    artist: 'El Greco',
    year: 1597,
    lat: 40.413888888,
    lng: -3.692222222,
    imageUrl: '/artworks/_oss/art-61.jpg',
    description: 'Located at Museo del Prado.',
    museumName: 'Museo del Prado',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q617629'
  },
  {
    id: 62,
    title: 'The Resurrection',
    artist: 'El Greco',
    year: 1597,
    lat: 40.413611,
    lng: -3.703056,
    imageUrl: '/artworks/_oss/art-62.jpg',
    description: 'Located at Museo de la Trinidad.',
    museumName: 'Museo de la Trinidad',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q617629'
  },
  {
    id: 63,
    title: 'The Plum',
    artist: 'Édouard Manet',
    year: 1878,
    lat: 38.891388888,
    lng: -77.02,
    imageUrl: '/artworks/_oss/art-63.jpg',
    description: 'Located at National Gallery of Art.',
    museumName: 'National Gallery of Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q731639'
  },
  {
    id: 64,
    title: 'Portrait of Luca Pacioli',
    artist: 'Jacopo de\' Barbari',
    year: 1497,
    lat: 40.86699,
    lng: 14.250346,
    imageUrl: '/artworks/_oss/art-64.jpg',
    description: 'Located at Museo di Capodimonte.',
    museumName: 'Museo di Capodimonte',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q732821'
  },
  {
    id: 65,
    title: 'Lamentation over the Dead Christ',
    artist: 'Sandro Botticelli',
    year: 1490,
    lat: 48.149583,
    lng: 11.571776,
    imageUrl: '/artworks/_oss/art-65.jpg',
    description: 'Located at Bavarian State Painting Collections.',
    museumName: 'Bavarian State Painting Collections',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q735326'
  },
  {
    id: 66,
    title: 'Narcissuss',
    artist: 'Caravaggio',
    year: 1600,
    lat: 41.902779717,
    lng: 12.489527499,
    imageUrl: '/artworks/_oss/art-66.jpg',
    description: 'Located at Galleria Nazionale d\'Arte Antica.',
    museumName: 'Galleria Nazionale d\'Arte Antica',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q746716'
  },
  {
    id: 67,
    title: 'Swimming',
    artist: 'Thomas Eakins',
    year: 1885,
    lat: 32.747867,
    lng: -97.368447,
    imageUrl: '/artworks/_oss/art-67.jpg',
    description: 'Located at Amon Carter Museum of American Art.',
    museumName: 'Amon Carter Museum of American Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q766212'
  },
  {
    id: 68,
    title: 'Ritratto di Lunia Czechowska con ventaglio',
    artist: 'Amedeo Modigliani',
    year: 1919,
    lat: 48.8643,
    lng: 2.2978,
    imageUrl: '/artworks/_oss/art-68.jpg',
    description: 'Located at Musée d\'art moderne de Paris.',
    museumName: 'Musée d\'art moderne de Paris',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q769461'
  },
  {
    id: 69,
    title: 'The Night Café in Arles',
    artist: 'Paul Gauguin',
    year: 1888,
    lat: 55.74702868,
    lng: 37.60602901,
    imageUrl: '/artworks/_oss/art-69.jpg',
    description: 'Located at Pushkin Museum of Fine Arts.',
    museumName: 'Pushkin Museum of Fine Arts',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q780986'
  },
  {
    id: 70,
    title: 'Antiochus and Stratonice',
    artist: 'Jean-Auguste-Dominique Ingres',
    year: 1840,
    lat: 49.193944444,
    lng: 2.485277777,
    imageUrl: '/artworks/_oss/art-70.jpg',
    description: 'Located at Condé Museum.',
    museumName: 'Condé Museum',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q783563'
  },
  {
    id: 71,
    title: 'The Order of Release',
    artist: 'John Everett Millais',
    year: 1852,
    lat: 51.508888888,
    lng: -0.128333333,
    imageUrl: '/artworks/_oss/art-71.jpg',
    description: 'Located at National Gallery.',
    museumName: 'National Gallery',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q822541'
  },
  {
    id: 72,
    title: 'Flaming June',
    artist: 'Frederic Leighton',
    year: 1895,
    lat: 18.003888888,
    lng: -66.616944444,
    imageUrl: '/artworks/_oss/art-72.jpg',
    description: 'Located at Museo de Arte de Ponce.',
    museumName: 'Museo de Arte de Ponce',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q846213'
  },
  {
    id: 73,
    title: 'The Marquesa de Pontejos',
    artist: 'Francisco Goya',
    year: 1786,
    lat: 38.891388888,
    lng: -77.02,
    imageUrl: '/artworks/_oss/art-73.jpg',
    description: 'Located at National Gallery of Art.',
    museumName: 'National Gallery of Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q860950'
  },
  {
    id: 74,
    title: 'Portrait of the Sisters Zénaïde and Charlotte Bonaparte',
    artist: 'Jacques-Louis David',
    year: 1821,
    lat: 34.0775,
    lng: -118.475,
    imageUrl: '/artworks/_oss/art-74.jpg',
    description: 'Located at J. Paul Getty Museum.',
    museumName: 'J. Paul Getty Museum',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q2961038'
  },
  {
    id: 75,
    title: 'Mystic Crucifixion',
    artist: 'Sandro Botticelli',
    year: 1500,
    lat: 42.37409,
    lng: -71.114358,
    imageUrl: '/artworks/_oss/art-75.jpg',
    description: 'Located at Fogg Museum.',
    museumName: 'Fogg Museum',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q3005527'
  },
  {
    id: 76,
    title: 'Blue Nude',
    artist: 'Henri Matisse',
    year: 1907,
    lat: 39.3259955,
    lng: -76.6195034,
    imageUrl: '/artworks/_oss/art-76.jpg',
    description: 'Located at Baltimore Museum of Art.',
    museumName: 'Baltimore Museum of Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q882584'
  },
  {
    id: 77,
    title: 'View of Toledo',
    artist: 'El Greco',
    year: 1596,
    lat: 40.779444444,
    lng: -73.963333333,
    imageUrl: '/artworks/_oss/art-77.jpg',
    description: 'Located at Metropolitan Museum of Art.',
    museumName: 'Metropolitan Museum of Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q883994'
  },
  {
    id: 78,
    title: 'Portrait of the Marchioness of Santa Cruz',
    artist: 'Francisco Goya',
    year: 1805,
    lat: 40.413888888,
    lng: -3.692222222,
    imageUrl: '/artworks/_oss/art-78.jpg',
    description: 'Located at Museo del Prado.',
    museumName: 'Museo del Prado',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q926809'
  },
  {
    id: 79,
    title: 'Portrait of Lorenzo di Credi',
    artist: 'Pietro Perugino',
    year: 1488,
    lat: 38.891388888,
    lng: -77.02,
    imageUrl: '/artworks/_oss/art-79.jpg',
    description: 'Located at National Gallery of Art.',
    museumName: 'National Gallery of Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q931933'
  },
  {
    id: 80,
    title: 'The Races at Longchamp',
    artist: 'Édouard Manet',
    year: 1866,
    lat: 41.879444444,
    lng: -87.623888888,
    imageUrl: '/artworks/_oss/art-80.jpg',
    description: 'Located at Art Institute of Chicago.',
    museumName: 'Art Institute of Chicago',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q942276'
  },
  {
    id: 81,
    title: 'Fray Hortensio Félix Paravicino',
    artist: 'El Greco',
    year: 1609,
    lat: 42.339444444,
    lng: -71.094166666,
    imageUrl: '/artworks/_oss/art-81.jpg',
    description: 'Located at Museum of Fine Arts Boston.',
    museumName: 'Museum of Fine Arts Boston',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q949323'
  },
  {
    id: 82,
    title: 'The Death of General Wolfe',
    artist: 'Benjamin West',
    year: 1770,
    lat: 45.429535,
    lng: -75.698906,
    imageUrl: '/artworks/_oss/art-82.jpg',
    description: 'Located at National Gallery of Canada.',
    museumName: 'National Gallery of Canada',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q956541'
  },
  {
    id: 83,
    title: 'Allegory of Virtue and Vice',
    artist: 'Paolo Veronese',
    year: 1565,
    lat: 40.771111111,
    lng: -73.967222222,
    imageUrl: '/artworks/_oss/art-83.jpg',
    description: 'Located at The Frick Collection.',
    museumName: 'The Frick Collection',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q961661'
  },
  {
    id: 84,
    title: 'Saint Jerome in the Wilderness',
    artist: 'Leonardo da Vinci',
    year: 1480,
    lat: 41.90573,
    lng: 12.45277,
    imageUrl: '/artworks/_oss/art-84.jpg',
    description: 'Located at Pinacoteca Vaticana.',
    museumName: 'Pinacoteca Vaticana',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q972196'
  },
  {
    id: 85,
    title: 'Blind Man\'s Bluff',
    artist: 'Jean-Honoré Fragonard',
    year: 1760,
    lat: 41.658333333,
    lng: -83.559444444,
    imageUrl: '/artworks/_oss/art-85.jpg',
    description: 'Located at Toledo Museum of Art.',
    museumName: 'Toledo Museum of Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q974414'
  },
  {
    id: 86,
    title: 'Poseuse de dos',
    artist: 'Georges Seurat',
    year: 1887,
    lat: 48.859972,
    lng: 2.326527,
    imageUrl: '/artworks/_oss/art-86.jpg',
    description: 'Located at Musée d\'Orsay.',
    museumName: 'Musée d\'Orsay',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q1119387'
  },
  {
    id: 87,
    title: 'Simultaneous Counter-Composition',
    artist: 'Theo van Doesburg',
    year: 1929,
    lat: 40.761444444,
    lng: -73.977611111,
    imageUrl: '/artworks/_oss/art-87.jpg',
    description: 'Located at Museum of Modern Art.',
    museumName: 'Museum of Modern Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q2613150'
  },
  {
    id: 88,
    title: 'Simultaneous Counter-Composition',
    artist: 'Theo van Doesburg',
    year: 1929,
    lat: 40.761666666,
    lng: -73.9775,
    imageUrl: '/artworks/_oss/art-88.jpg',
    description: 'Located at Museum of Modern Art.',
    museumName: 'Museum of Modern Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q2613150'
  },
  {
    id: 89,
    title: 'Composition VIII (The Cow)',
    artist: 'Theo van Doesburg',
    year: 1918,
    lat: 40.761666666,
    lng: -73.9775,
    imageUrl: '/artworks/_oss/art-89.jpg',
    description: 'Located at Museum of Modern Art.',
    museumName: 'Museum of Modern Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q2648692'
  },
  {
    id: 90,
    title: 'Madame X (Virginie Amélie Avegno Gautreau)',
    artist: 'John Singer Sargent',
    year: 1884,
    lat: 40.779444444,
    lng: -73.963333333,
    imageUrl: '/artworks/_oss/art-90.jpg',
    description: 'Located at Metropolitan Museum of Art.',
    museumName: 'Metropolitan Museum of Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q2664039'
  },
  {
    id: 91,
    title: 'Christ Falling on the Way to Calvary',
    artist: 'Raphael',
    year: 1515,
    lat: 40.413888888,
    lng: -3.692222222,
    imageUrl: '/artworks/_oss/art-91.jpg',
    description: 'Located at Museo del Prado.',
    museumName: 'Museo del Prado',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q2664637'
  },
  {
    id: 92,
    title: 'Martha and Mary Magdalene',
    artist: 'Caravaggio',
    year: 1598,
    lat: 42.359444444,
    lng: -83.064722222,
    imageUrl: '/artworks/_oss/art-92.jpg',
    description: 'Located at Detroit Institute of Arts.',
    museumName: 'Detroit Institute of Arts',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q2734679'
  },
  {
    id: 93,
    title: 'Self-portrait with Dr Arrieta',
    artist: 'Francisco Goya',
    year: 1820,
    lat: 44.958611111,
    lng: -93.274166666,
    imageUrl: '/artworks/_oss/art-93.jpg',
    description: 'Located at Minneapolis Institute of Art.',
    museumName: 'Minneapolis Institute of Art',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q2736720'
  },
  {
    id: 94,
    title: 'Counter-composition XIII',
    artist: 'Theo van Doesburg',
    year: 1925,
    lat: 45.43083,
    lng: 12.33154,
    imageUrl: '/artworks/_oss/art-94.jpg',
    description: 'Located at Peggy Guggenheim Collection.',
    museumName: 'Peggy Guggenheim Collection',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q2751557'
  },
  {
    id: 95,
    title: 'The Battle of Zurich, 25th September 1799',
    artist: 'François Bouchot',
    year: 1835,
    lat: 48.8044,
    lng: 2.12197,
    imageUrl: '/artworks/_oss/art-95.jpg',
    description: 'Located at Museum of the History of France.',
    museumName: 'Museum of the History of France',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q2890444'
  },
  {
    id: 96,
    title: 'Eugenia Martinez Valleji, called La Monstrua',
    artist: 'Juan Carreño de Miranda',
    year: 1680,
    lat: 40.413888888,
    lng: -3.692222222,
    imageUrl: '/artworks/_oss/art-96.jpg',
    description: 'Located at Museo del Prado.',
    museumName: 'Museo del Prado',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q2890595'
  },
  {
    id: 97,
    title: 'The Tub',
    artist: 'Edgar Degas',
    year: 1886,
    lat: 48.86,
    lng: 2.326388888,
    imageUrl: '/artworks/_oss/art-97.jpg',
    description: 'Located at Musée d\'Orsay.',
    museumName: 'Musée d\'Orsay',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q2912117'
  },
  {
    id: 98,
    title: 'The Tub',
    artist: 'Edgar Degas',
    year: 1886,
    lat: 48.859972,
    lng: 2.326527,
    imageUrl: '/artworks/_oss/art-98.jpg',
    description: 'Located at Musée d\'Orsay.',
    museumName: 'Musée d\'Orsay',
    source: 'wikidata',
    sourceUrl: 'http://www.wikidata.org/entity/Q2912117'
  }
]

export const easternArtData = [
  {
    id: 'e1',
    title: 'The Great Wave off Kanagawa',
    artist: 'Katsushika Hokusai',
    lat: 35.7187,
    lng: 139.7765,
    imageUrl: '/artworks/asia/asia-8c1227960ebcc041.jpg',
    canonicalImageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Great_Wave_off_Kanagawa.jpg?width=640',
    description: 'Iconic woodblock print depicting a massive wave threatening boats off the coast of Sagami Bay.',
    museumName: 'Tokyo National Museum',
    
  },
  {
    id: 'e2',
    title: 'Pine Trees (Shōrin-zu byōbu)',
    artist: 'Hasegawa Tōhaku',
    lat: 35.7187,
    lng: 139.7765,
    imageUrl: '/artworks/asia/asia-f368f398996a2706.jpg',
    canonicalImageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pine_Trees.jpg?width=640',
    description: 'A masterpiece of Japanese ink painting (suibokuga) showing pine trees in the mist.',
    museumName: 'Tokyo National Museum',
    
  },
  {
    id: 'e3',
    title: 'Fugen Bosatsu (Samantabhadra)',
    artist: 'Unknown (Heian Period)',
    lat: 35.7187,
    lng: 139.7765,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Fugen_Bosatsu(Samantabhadra)_-_Google_Art_Project.jpg?width=800',
    description: 'A serene Buddhist painting of the Bodhisattva of Universal Virtue riding a white elephant.',
    museumName: 'Tokyo National Museum',
    
  },
  {
    id: 'e4',
    title: 'Wind God and Thunder God',
    artist: 'Tawaraya Sōtatsu',
    lat: 34.99,
    lng: 135.7725,
    imageUrl: '/artworks/asia/asia-d96cf268653bf98a.png',
    canonicalImageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Wind_God_and_Thunder_God_Screens_by_Tawaraya_Sotatsu_hi-res.png?width=640',
    description: 'A highly dynamic pair of two-fold screens depicting the Shinto gods of wind and thunder.',
    museumName: 'Kyoto National Museum',
    
  },
  {
    id: 'e5',
    title: 'Jadeite Cabbage',
    artist: 'Unknown (Qing Dynasty)',
    lat: 25.102,
    lng: 121.5485,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Jadeite_cabbage_(2).jpg?width=800',
    description: 'A piece of jadeite carved into the shape of a bok choy cabbage with a locust and katydid hiding in the leaves.',
    museumName: 'National Palace Museum',
    
  },
  {
    id: 'e6',
    title: 'Meat-Shaped Stone',
    artist: 'Unknown (Qing Dynasty)',
    lat: 25.102,
    lng: 121.5485,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Meat-shaped_Stone_(Jasper)_(27228557209).jpg?width=800',
    description: 'A piece of jasper carved and dyed to resemble a piece of Dongpo pork.',
    museumName: 'National Palace Museum',
    
  },
  {
    id: 'e7',
    title: 'Dwelling in the Fuchun Mountains',
    artist: 'Huang Gongwang',
    lat: 25.102,
    lng: 121.5485,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Dwelling_in_the_Fuchun_Mountains_(second_half).jpg?width=800',
    description: 'One of the most famous surviving Chinese landscape paintings, created in the 14th century.',
    museumName: 'National Palace Museum',
    
  },
  {
    id: 'e8',
    title: 'Along the River During the Qingming Festival',
    artist: 'Zhang Zeduan',
    lat: 39.9163,
    lng: 116.3972,
    imageUrl: '/artworks/asia/asia-28b7d1e36965c79e.jpg',
    canonicalImageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Alongtheriver_QingMing.jpg?width=640',
    description: 'A massive panoramic scroll capturing the daily life of people and the landscape of the capital, Bianjing.',
    museumName: 'Palace Museum, Beijing',
    
  },
  {
    id: 'e9',
    title: 'A Thousand Li of Rivers and Mountains',
    artist: 'Wang Ximeng',
    lat: 39.9163,
    lng: 116.3972,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Wang_Ximeng_-_A_Thousand_Li_of_River_(Bridge).jpg?width=800',
    description: 'A breathtaking blue-and-green landscape scroll painted when the artist was only 18 years old.',
    museumName: 'Palace Museum, Beijing',
    
  },
  {
    id: 'e10',
    title: 'Da Ke Ding',
    artist: 'Unknown (Western Zhou Dynasty)',
    lat: 31.2294,
    lng: 121.47,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Da_Ke_ding.jpg?width=800',
    description: 'A massive ancient Chinese bronze ritual food vessel with extensive inscriptions.',
    museumName: 'Shanghai Museum',
    
  },
  {
    id: 'e11',
    title: 'Pensive Bodhisattva',
    artist: 'Unknown (Silla Kingdom)',
    lat: 37.5239,
    lng: 126.9805,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pensive_Bodhisattva_(National_Treasure_No._78)_01.jpg?width=800',
    description: 'A gilt-bronze statue of Maitreya in deep thought, representing the pinnacle of Korean Buddhist sculpture.',
    museumName: 'National Museum of Korea',
    
  },
  {
    id: 'e12',
    title: 'Celadon Incense Burner',
    artist: 'Unknown (Goryeo Dynasty)',
    lat: 37.5239,
    lng: 126.9805,
    imageUrl: '/artworks/asia/asia-cd39821edcda768d.jpg',
    canonicalImageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Korea_-_Seoul_-_National_Museum_-_Incense_Burner_0252-06a.jpg?width=640',
    description: 'An exquisite example of Goryeo celadon, featuring intricate openwork and a kingfisher glaze.',
    museumName: 'National Museum of Korea',
    
  },
  {
    id: 'e13',
    title: 'Dancing Girl of Mohenjo-Daro',
    artist: 'Unknown (Indus Valley Civilization)',
    lat: 28.6119,
    lng: 77.2193,
    imageUrl: '/artworks/asia/asia-3b1b22b86ce70dc7.jpg',
    canonicalImageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Dancing_girl_of_Mohenjo-daro.jpg?width=640',
    description: 'A prehistoric bronze statuette dating back to 2300 BC, showing remarkable metallurgical skill.',
    museumName: 'National Museum, New Delhi',
    
  },
  {
    id: 'e14',
    title: 'Nataraja (Lord of the Dance)',
    artist: 'Unknown (Chola Dynasty)',
    lat: 28.6119,
    lng: 77.2193,
    imageUrl: '/artworks/asia/asia-038a6ff3611a04fd.jpg',
    canonicalImageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Shiva_as_Lord_of_the_Dance_(Nataraja).jpg?width=640',
    description: 'A stunning bronze sculpture of the Hindu god Shiva performing the cosmic dance.',
    museumName: 'National Museum, New Delhi',
    
  },
  {
    id: 'e15',
    title: 'Emperor Jahangir Weighing Prince Khurram',
    artist: 'Manohar',
    lat: 28.6119,
    lng: 77.2193,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Jahangir_weighing_prince_Khurram_(later_Shah_Jahan)_against_gold_and_silver_in_the_presence_of_Mahabat_Khan_and_Khan_Jahan..jpg?width=800',
    description: 'A highly detailed Mughal miniature painting depicting a royal weighing ceremony.',
    museumName: 'National Museum, New Delhi',
    
  },
  {
    id: 'e16',
    title: 'The Shahnameh of Shah Tahmasp (Folio)',
    artist: 'Various Royal Ateliers',
    lat: 25.2955,
    lng: 51.5395,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Folio_153v_from_the_Shahnama_of_Shah_Tahmasp_TMoCA.jpg?width=800',
    description: 'An incredibly intricate illuminated manuscript page from the Persian epic, the Book of Kings.',
    museumName: 'Museum of Islamic Art, Doha',
    
  },
  {
    id: 'e17',
    title: 'Planispheric Astrolabe',
    artist: 'Hamid ibn Mahmud al-Isfahani',
    lat: 25.2955,
    lng: 51.5395,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/MIA_-_Planispheric_Astrolabe,_Iran,_984_AD.jpg?width=800',
    description: 'A beautifully crafted brass astronomical instrument used in the medieval Islamic world.',
    museumName: 'Museum of Islamic Art, Doha',
    
  },
  {
    id: 'e18',
    title: 'Topkapi Dagger',
    artist: 'Ottoman Court Jewelers',
    lat: 41.0115,
    lng: 28.9833,
    imageUrl: '/artworks/asia/asia-9a73ec089f7f80f1.jpg',
    canonicalImageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Topkapi_Knife_04_1993.jpg?width=640',
    description: 'A magnificent dagger featuring three massive emeralds on the hilt and a watch hidden in the pommel.',
    museumName: 'Topkapi Palace Museum',
    
  },
  {
    id: 'e19',
    title: 'Spoonmaker\'s Diamond',
    artist: 'Unknown',
    lat: 41.0115,
    lng: 28.9833,
    imageUrl: '/artworks/asia/asia-7b6ca2629bf51ef0.jpg',
    canonicalImageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Spoonmaker%27s_Diamond.jpg?width=640',
    description: 'An 86-carat pear-shaped diamond, one of the most famous jewels of the Ottoman Empire.',
    museumName: 'Topkapi Palace Museum',
    
  },
  {
    id: 'e20',
    title: 'Bronze Rhinoceros Vessel',
    artist: 'Unknown (Shang Dynasty)',
    lat: 37.7802,
    lng: -122.4162,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bronze_Rhino_(8216203650).jpg?width=800',
    description: 'A rare and highly realistic bronze ritual vessel in the shape of a two-horned rhinoceros.',
    museumName: 'Asian Art Museum (SF)',
    
  }
]
